/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gpa;

import java.awt.TextField;
import java.awt.Toolkit;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javafx.scene.layout.BorderStroke;
import javax.swing.JFrame;


/**
 *
 * @author Isuru Madhushan
 */
public class gpa2 extends javax.swing.JFrame {

  public static int subnum2;
  
  public static int c1i,c2i,c3i,c4i,c5i,c6i,c7i,c8i,c9i,c10i;
  public static double r1i,r2i,r3i,r4i,r5i,r6i,r7i,r8i,r9i,r10i;
  public static String r1s,r2s,r3s,r4s,r5s,r6s,r7s,r8s,r9s,r10s;
  public static double sumc;
  public static double gpas;
  
  public static String yy;
  
  public static String sub1name;
  public static String sub2name;
  public static String sub3name;
  public static String sub4name;
  public static String sub5name;
  public static String sub6name;
  public static String sub7name;
  public static String sub8name;
  public static String sub9name;
  public static String sub10name;
  
  public String name3;
public String rnumber3;
public String uniname3;
public String yearsem3;

//previous details//

int subnumz;
String namez,rnumberz,uninamez,yearsemz;
String sub1,sub2,sub3,sub4,sub5,sub6,sub7,sub8,sub9,sub10;
String res1,res2,res3,res4,res5,res6,res7,res8,res9,res10;
int C1,C2,C3,C4,C5,C6,C7,C8,C9,C10;


  
  
 

    
   
    /**
     * Creates new form 
     */
    public gpa2() {
        initComponents();
        setTitle("GPA Calculator");
        setIcon() ;
        t1.grabFocus();
        setExtendedState(6);
        setResizable(false);
     }
    
    public gpa2(int x,String a,String b,String c,String d){
     initComponents();
     setIcon() ;
     setExtendedState(6);   
     setResizable(false);
     setTitle("GPA Calculator");
        t1.grabFocus();
         subnum2=x;
         name3=a;
         rnumber3=b;
         uniname3=c;
         yearsem3=d;
         
         autogen();
    }
    
    public gpa2(int x,String a,String b,String c,String d,String s1,String s2,String s3,String s4,String s5,String s6,String s7,String s8,
                String s9,String s10,String r1,String r2,String r3,String r4,String r5,String r6,String r7,String r8,String r9,String r10,
                int c1,int c2,int c3,int c4,int c5,int c6,int c7,int c8,int c9,int c10){
        
        initComponents();
     setExtendedState(6); 
     setIcon() ;
     setResizable(false);
     setTitle("GPA Calculator");
     
     subnumz=x;
     namez=a;
     rnumberz=b;
     uninamez=c;
     yearsemz=d;
     
     
     
     sub1=s1;
     sub2=s2;
     sub3=s3;
     sub4=s4;
     sub5=s5;
     sub6=s6;
     sub7=s7;
     sub8=s8;
     sub9=s9;
     sub10=s10;
     
        C1=c1;
        C2=c2;
        C3=c3;
        C4=c4;
        C5=c5;
        C6=c6;
        C7=c7;
        C8=c8;
        C9=c9;
        C10=c10;
        
        res1=r1;
        res2=r2;
        res3=r3;
        res4=r4;
        res5=r5;
        res6=r6;
        res7=r7;
        res8=r8;
        res9=r9;
        res10=r10;
        
        
        autogenprevious();
        
        textautogenpre();
        
     
    
    }
  
   
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gexit = new javax.swing.JButton();
        gpre = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        c3 = new javax.swing.JComboBox<>();
        c4 = new javax.swing.JComboBox<>();
        c5 = new javax.swing.JComboBox<>();
        c6 = new javax.swing.JComboBox<>();
        c7 = new javax.swing.JComboBox<>();
        c8 = new javax.swing.JComboBox<>();
        c9 = new javax.swing.JComboBox<>();
        c10 = new javax.swing.JComboBox<>();
        r2 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JComboBox<>();
        r3 = new javax.swing.JComboBox<>();
        r4 = new javax.swing.JComboBox<>();
        r5 = new javax.swing.JComboBox<>();
        r6 = new javax.swing.JComboBox<>();
        r7 = new javax.swing.JComboBox<>();
        r10 = new javax.swing.JComboBox<>();
        r8 = new javax.swing.JComboBox<>();
        r9 = new javax.swing.JComboBox<>();
        r1 = new javax.swing.JComboBox<>();
        t8 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        gnext1 = new javax.swing.JButton();
        net = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 51));
        jLabel2.setText("GPA Calculator");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 570, 100));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Credit");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        gexit.setBackground(new java.awt.Color(0, 153, 204));
        gexit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        gexit.setForeground(new java.awt.Color(204, 204, 204));
        gexit.setText("Exit");
        gexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gexitActionPerformed(evt);
            }
        });
        getContentPane().add(gexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 230, 60));

        gpre.setBackground(new java.awt.Color(0, 153, 204));
        gpre.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        gpre.setForeground(new java.awt.Color(204, 204, 204));
        gpre.setText("Previous");
        gpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpreActionPerformed(evt);
            }
        });
        gpre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gpreKeyPressed(evt);
            }
        });
        getContentPane().add(gpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 380, 230, 60));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Result");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Subject Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        c2.setBackground(new java.awt.Color(255, 255, 102));
        c2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        c3.setBackground(new java.awt.Color(255, 255, 102));
        c3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        c4.setBackground(new java.awt.Color(255, 255, 102));
        c4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        c5.setBackground(new java.awt.Color(255, 255, 102));
        c5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        c6.setBackground(new java.awt.Color(255, 255, 102));
        c6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        c7.setBackground(new java.awt.Color(255, 255, 102));
        c7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        c8.setBackground(new java.awt.Color(255, 255, 102));
        c8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        c9.setBackground(new java.awt.Color(255, 255, 102));
        c9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, -1, -1));

        c10.setBackground(new java.awt.Color(255, 255, 102));
        c10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        getContentPane().add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, -1, -1));

        r2.setBackground(new java.awt.Color(51, 255, 255));
        r2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, -1, -1));

        c1.setBackground(new java.awt.Color(255, 255, 102));
        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  0", "  1", "  2", "  3", "  4", " " }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        r3.setBackground(new java.awt.Color(51, 255, 255));
        r3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, -1, -1));

        r4.setBackground(new java.awt.Color(51, 255, 255));
        r4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, -1, -1));

        r5.setBackground(new java.awt.Color(51, 255, 255));
        r5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, -1, -1));

        r6.setBackground(new java.awt.Color(51, 255, 255));
        r6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, -1, -1));

        r7.setBackground(new java.awt.Color(51, 255, 255));
        r7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, -1, -1));

        r10.setBackground(new java.awt.Color(51, 255, 255));
        r10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 660, -1, -1));

        r8.setBackground(new java.awt.Color(51, 255, 255));
        r8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, -1, -1));

        r9.setBackground(new java.awt.Color(51, 255, 255));
        r9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, -1, -1));

        r1.setBackground(new java.awt.Color(51, 255, 255));
        r1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E", " " }));
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 210, -1, -1));

        t8.setBackground(new java.awt.Color(204, 102, 255));
        t8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 370, 30));

        t7.setBackground(new java.awt.Color(204, 102, 255));
        t7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 370, 30));

        t9.setBackground(new java.awt.Color(204, 102, 255));
        t9.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 370, 30));

        t6.setBackground(new java.awt.Color(204, 102, 255));
        t6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 370, 30));

        t3.setBackground(new java.awt.Color(204, 102, 255));
        t3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 370, 30));

        t5.setBackground(new java.awt.Color(204, 102, 255));
        t5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 370, 30));

        t1.setBackground(new java.awt.Color(204, 102, 255));
        t1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 370, 30));

        t4.setBackground(new java.awt.Color(204, 102, 255));
        t4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 370, 30));

        t10.setBackground(new java.awt.Color(204, 102, 255));
        t10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, 370, 30));

        t2.setBackground(new java.awt.Color(204, 102, 255));
        t2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 370, 30));

        gnext1.setBackground(new java.awt.Color(0, 153, 204));
        gnext1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        gnext1.setForeground(new java.awt.Color(204, 204, 204));
        gnext1.setText("Next");
        gnext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnext1ActionPerformed(evt);
            }
        });
        getContentPane().add(gnext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 230, 60));

        net.setBackground(new java.awt.Color(255, 255, 102));
        net.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        net.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gpa/dddddd.jpg"))); // NOI18N
        getContentPane().add(net, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1360, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    public void credit(){
      c1i=(Integer) c1.getSelectedIndex();
       c2i=(Integer) c2.getSelectedIndex();
        c3i=(Integer) c3.getSelectedIndex();
         c4i=(Integer) c4.getSelectedIndex();
          c5i=(Integer) c5.getSelectedIndex();
           c6i=(Integer) c6.getSelectedIndex(); 
            c7i=(Integer) c7.getSelectedIndex();
             c8i=(Integer) c8.getSelectedIndex();
              c9i=(Integer) c9.getSelectedIndex();
               c10i=(Integer) c10.getSelectedIndex();
           
      
    }
    
    public  void point(){
       r1s=(String) r1.getSelectedItem();
       r2s=(String) r2.getSelectedItem();
       r3s=(String) r3.getSelectedItem();
       r4s=(String) r4.getSelectedItem();
       r5s=(String) r5.getSelectedItem();
       r6s=(String) r6.getSelectedItem();
       r7s=(String) r7.getSelectedItem();
       r8s=(String) r8.getSelectedItem();
       r9s=(String) r9.getSelectedItem();
       r10s=(String) r10.getSelectedItem();
       
        
        r1id();
        r2id();
        r3id();
        r4id();
        r5id();
        r6id();
        r7id();
        r8id();
        r9id();
        r10id();
        
       
       
    }
    public void r1id(){
       if(r1s.equals("A") || r1s.equals("A+")){
         r1i=4.0;
       }
       else if(r1s.equals("A-")){
         r1i=3.7;
       }
       else if(r1s.equals("B+")){
       r1i=3.3;
       }
       else if(r1s.equals("B")){
       r1i=3.0;
       }
       else if(r1s.equals("B-")){
       r1i=2.7;
       }
       else if(r1s.equals("C+")){
       r1i=2.3;
       }
       else if(r1s.equals("C")){
       r1i=2;
       }
       else if(r1s.equals("C-")){
       r1i=1.7;
       }
       else if(r1s.equals("D+")){
       r1i=1.3;
       }
       else if(r1s.equals("D")){
       r1i=1;
       }
       else if(r1s.equals("E")){
       r1i=0;
       }
    }
    
    public void r2id(){
       if(r2s.equals("A") || r2s.equals("A+")){
         r2i=4.0;
       }
       else if(r2s.equals("A-")){
         r2i=3.7;
       }
       else if(r2s.equals("B+")){
       r2i=3.3;
       }
       else if(r2s.equals("B")){
       r2i=3.0;
       }
       else if(r2s.equals("B-")){
       r2i=2.7;
       }
       else if(r2s.equals("C+")){
       r2i=2.3;
       }
       else if(r2s.equals("C")){
       r2i=2;
       }
       else if(r2s.equals("C-")){
       r2i=1.7;
       }
       else if(r2s.equals("D+")){
       r2i=1.3;
       }
       else if(r2s.equals("D")){
       r2i=1;
       }
       else if(r2s.equals("E")){
       r2i=0;
       }
    }
    
    public void r3id(){
       if(r3s.equals("A") || r3s.equals("A+")){
         r3i=4.0;
       }
       else if(r3s.equals("A-")){
         r3i=3.7;
       }
       else if(r3s.equals("B+")){
       r3i=3.3;
       }
       else if(r3s.equals("B")){
       r3i=3.0;
       }
       else if(r3s.equals("B-")){
       r3i=2.7;
       }
       else if(r3s.equals("C+")){
       r3i=2.3;
       }
       else if(r3s.equals("C")){
       r3i=2;
       }
       else if(r3s.equals("C-")){
       r3i=1.7;
       }
       else if(r3s.equals("D+")){
       r3i=1.3;
       }
       else if(r3s.equals("D")){
       r3i=1;
       }
       else if(r3s.equals("E")){
       r3i=0;
       }
    }
    
    public void r4id(){
       if(r4s.equals("A") || r4s.equals("A+")){
         r4i=4.0;
       }
       else if(r4s.equals("A-")){
         r4i=3.7;
       }
       else if(r4s.equals("B+")){
       r4i=3.3;
       }
       else if(r4s.equals("B")){
       r4i=3.0;
       }
       else if(r4s.equals("B-")){
       r4i=2.7;
       }
       else if(r4s.equals("C+")){
       r4i=2.3;
       }
       else if(r4s.equals("C")){
       r4i=2;
       }
       else if(r4s.equals("C-")){
       r4i=1.7;
       }
       else if(r4s.equals("D+")){
       r4i=1.3;
       }
       else if(r4s.equals("D")){
       r4i=1;
       }
       else if(r4s.equals("E")){
       r4i=0;
       }
    }
    public void r5id(){
       if(r5s.equals("A") || r5s.equals("A+")){
         r5i=4.0;
       }
       else if(r5s.equals("A-")){
         r5i=3.7;
       }
       else if(r5s.equals("B+")){
       r5i=3.3;
       }
       else if(r5s.equals("B")){
       r5i=3.0;
       }
       else if(r5s.equals("B-")){
       r5i=2.7;
       }
       else if(r5s.equals("C+")){
       r5i=2.3;
       }
       else if(r5s.equals("C")){
       r5i=2;
       }
       else if(r5s.equals("C-")){
       r5i=1.7;
       }
       else if(r5s.equals("D+")){
       r5i=1.3;
       }
       else if(r5s.equals("D")){
       r5i=1;
       }
       else if(r5s.equals("E")){
       r5i=0;
       }
    }
    public void r6id(){
       if(r6s.equals("A") || r6s.equals("A+")){
         r6i=4.0;
       }
       else if(r6s.equals("A-")){
         r6i=3.7;
       }
       else if(r6s.equals("B+")){
       r6i=3.3;
       }
       else if(r6s.equals("B")){
       r6i=3.0;
       }
       else if(r6s.equals("B-")){
       r6i=2.7;
       }
       else if(r6s.equals("C+")){
       r6i=2.3;
       }
       else if(r6s.equals("C")){
       r6i=2;
       }
       else if(r6s.equals("C-")){
       r6i=1.7;
       }
       else if(r6s.equals("D+")){
       r6i=1.3;
       }
       else if(r6s.equals("D")){
       r6i=1;
       }
       else if(r6s.equals("E")){
       r6i=0;
       }
    }
    public void r7id(){
       if(r7s.equals("A") || r7s.equals("A+")){
         r7i=4.0;
       }
       else if(r7s.equals("A-")){
         r7i=3.7;
       }
       else if(r7s.equals("B+")){
       r7i=3.3;
       }
       else if(r7s.equals("B")){
       r7i=3.0;
       }
       else if(r7s.equals("B-")){
       r7i=2.7;
       }
       else if(r7s.equals("C+")){
       r7i=2.3;
       }
       else if(r7s.equals("C")){
       r7i=2;
       }
       else if(r7s.equals("C-")){
       r7i=1.7;
       }
       else if(r7s.equals("D+")){
       r7i=1.3;
       }
       else if(r7s.equals("D")){
       r7i=1;
       }
       else if(r7s.equals("E")){
       r7i=0;
       }
    }
    public void r8id(){
       if(r8s.equals("A") || r8s.equals("A+")){
         r8i=4.0;
       }
       else if(r8s.equals("A-")){
         r8i=3.7;
       }
       else if(r8s.equals("B+")){
       r8i=3.3;
       }
       else if(r8s.equals("B")){
       r8i=3.0;
       }
       else if(r8s.equals("B-")){
       r8i=2.7;
       }
       else if(r8s.equals("C+")){
       r8i=2.3;
       }
       else if(r8s.equals("C")){
       r8i=2;
       }
       else if(r8s.equals("C-")){
       r8i=1.7;
       }
       else if(r8s.equals("D+")){
       r8i=1.3;
       }
       else if(r8s.equals("D")){
       r8i=1;
       }
       else if(r8s.equals("E")){
       r8i=0;
       }
    }
    
     public void r9id(){
       if(r9s.equals("A") || r9s.equals("A+")){
         r9i=4.0;
       }
       else if(r9s.equals("A-")){
         r9i=3.7;
       }
       else if(r9s.equals("B+")){
       r9i=3.3;
       }
       else if(r9s.equals("B")){
       r9i=3.0;
       }
       else if(r9s.equals("B-")){
       r9i=2.7;
       }
       else if(r9s.equals("C+")){
       r9i=2.3;
       }
       else if(r9s.equals("C")){
       r9i=2;
       }
       else if(r9s.equals("C-")){
       r9i=1.7;
       }
       else if(r9s.equals("D+")){
       r9i=1.3;
       }
       else if(r9s.equals("D")){
       r9i=1;
       }
       else if(r9s.equals("E")){
       r9i=0;
       }
    }
     
      public void r10id(){
       if(r10s.equals("A") || r10s.equals("A+")){
         r10i=4.0;
       }
       else if(r10s.equals("A-")){
         r10i=3.7;
       }
       else if(r10s.equals("B+")){
       r10i=3.3;
       }
       else if(r10s.equals("B")){
       r10i=3.0;
       }
       else if(r10s.equals("B-")){
       r10i=2.7;
       }
       else if(r10s.equals("C+")){
       r10i=2.3;
       }
       else if(r10s.equals("C")){
       r10i=2;
       }
       else if(r10s.equals("C-")){
       r10i=1.7;
       }
       else if(r10s.equals("D+")){
       r10i=1.3;
       }
       else if(r10s.equals("D")){
       r10i=1;
       }
       else if(r10s.equals("E")){
       r10i=0;
       }
    }
     
    
    public void autogen(){
     if(subnum2==10){
         
    }
     else if(subnum2==9){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          
     }
     else if(subnum2==8){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
     }
     else if(subnum2==7){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          
     }
     else if(subnum2==6){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
     }
     else if(subnum2==5){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
     }
     else if(subnum2==4){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
     }
     else if(subnum2==3){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
          t4.setVisible(false);  c4.setVisible(false);   r4.setVisible(false);
          
     }
     else if(subnum2==2){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
          t4.setVisible(false);  c4.setVisible(false);   r4.setVisible(false);
          t3.setVisible(false);  c3.setVisible(false);   r3.setVisible(false);
          
     }
     else if(subnum2==1){
            t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
          t4.setVisible(false);  c4.setVisible(false);   r4.setVisible(false);
          t3.setVisible(false);  c3.setVisible(false);   r3.setVisible(false);
          t2.setVisible(false);  c2.setVisible(false);   r2.setVisible(false);
     }
   }
    
    public void sumasion(){
        
        credit();
         point();
    sumc=c1i+c2i+c3i+c4i+c5i+c6i+c7i+c8i+c9i+c10i;
       
     gpas=(c1i*r1i+c2i*r2i +c3i*r3i+c4i*r4i+c5i*r5i+c6i*r6i+c7i*r7i+c8i*r8i+c9i*r9i+c10i*r10i)/sumc;
     
      
             DecimalFormat df = new DecimalFormat("#.##");
      df.setRoundingMode(RoundingMode.FLOOR);
          yy = df.format(gpas);
         
          
             
    }
    
    public void autogenprevious(){
     if(subnum2==10){
         
    }
     else if(subnum2==9){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          
     }
     else if(subnum2==8){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
     }
     else if(subnum2==7){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          
     }
     else if(subnum2==6){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
     }
     else if(subnum2==5){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
     }
     else if(subnum2==4){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
     }
     else if(subnum2==3){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
          t4.setVisible(false);  c4.setVisible(false);   r4.setVisible(false);
          
     }
     else if(subnum2==2){
          t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
          t4.setVisible(false);  c4.setVisible(false);   r4.setVisible(false);
          t3.setVisible(false);  c3.setVisible(false);   r3.setVisible(false);
          
     }
     else if(subnum2==1){
            t10.setVisible(false);  c10.setVisible(false);   r10.setVisible(false);
          t9.setVisible(false);  c9.setVisible(false);   r9.setVisible(false);
          t8.setVisible(false);  c8.setVisible(false);   r8.setVisible(false);
          t7.setVisible(false);  c7.setVisible(false);   r7.setVisible(false);
          t6.setVisible(false);  c6.setVisible(false);   r6.setVisible(false);
          t5.setVisible(false);  c5.setVisible(false);   r5.setVisible(false);
          t4.setVisible(false);  c4.setVisible(false);   r4.setVisible(false);
          t3.setVisible(false);  c3.setVisible(false);   r3.setVisible(false);
          t2.setVisible(false);  c2.setVisible(false);   r2.setVisible(false);
     }
    }
    
    public void textautogenpre(){
    t1.setText(sub1);      c1.setSelectedIndex(C1);  r1.setSelectedItem(res1); 
     t2.setText(sub2);      c2.setSelectedIndex(C2);  r2.setSelectedItem(res2);
      t3.setText(sub3);      c3.setSelectedIndex(C3);  r3.setSelectedItem(res3);
       t4.setText(sub4);      c4.setSelectedIndex(C4);  r4.setSelectedItem(res4);
        t5.setText(sub5);      c5.setSelectedIndex(C5);  r5.setSelectedItem(res5);
         t6.setText(sub6);      c6.setSelectedIndex(C6);  r6.setSelectedItem(res6);
          t7.setText(sub7);      c7.setSelectedIndex(C7);  r7.setSelectedItem(res7);
           t8.setText(sub8);      c8.setSelectedIndex(C8);  r8.setSelectedItem(res8);
            t9.setText(sub9);      c9.setSelectedIndex(C9);  r9.setSelectedItem(res9);
             t10.setText(sub10);      c10.setSelectedIndex(C10);  r10.setSelectedItem(res10); 
           
   }
    
    
    
    private void gexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gexitActionPerformed
       this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_gexitActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t10ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void gpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpreActionPerformed
             if(subnumz==0){
              gpai g11=new gpai(subnum2,name3,rnumber3,uniname3,yearsem3);
             
             
             g11.setVisible(true);
             this.dispose();
             }
             else{
             gpai g11=new gpai(subnumz,namez,rnumberz,uninamez,yearsemz);
             
             
             g11.setVisible(true);
             this.dispose();
             }
       // TODO add your handling code here:
    }//GEN-LAST:event_gpreActionPerformed

    
    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed
  
  
 
    private void gnext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnext1ActionPerformed
      
        
       sumasion();
       sub1name=t1.getText();
    sub2name=t2.getText();
    sub3name=t3.getText();
    sub4name=t4.getText();
    sub5name=t5.getText();
    sub6name=t6.getText();
    sub7name=t7.getText();
    sub8name=t8.getText();
    sub9name=t9.getText();
    sub10name=t10.getText();
    
    if(subnumz!=0){
    gpa3 g4=new gpa3(namez,rnumberz,uninamez,yearsemz,sub1name,sub2name,sub3name,sub4name,sub5name,sub6name,sub7name,
              sub8name,sub9name,sub10name,yy,r1s,r2s,r3s,r4s,r5s,r6s,r7s,r8s,r9s,r10s,subnumz,c1i,c2i,c3i,c4i,c5i,c6i,c7i,c8i,c9i,c10i);
      
      
      g4.setVisible(true);
      this.dispose();
    }
    
    else{
      
     
      gpa3 g4=new gpa3(name3,rnumber3,uniname3,yearsem3,sub1name,sub2name,sub3name,sub4name,sub5name,sub6name,sub7name,
              sub8name,sub9name,sub10name,yy,r1s,r2s,r3s,r4s,r5s,r6s,r7s,r8s,r9s,r10s,subnum2,c1i,c2i,c3i,c4i,c5i,c6i,c7i,c8i,c9i,c10i);
      
      
      g4.setVisible(true);
      this.dispose();
    }
        
    }//GEN-LAST:event_gnext1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void gpreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpreKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gpa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gpa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gpa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gpa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gpa2().setVisible(true);
            }
        });
        
        
       
    }
     private void setIcon(){
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("download.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> c1;
    public javax.swing.JComboBox<String> c10;
    public javax.swing.JComboBox<String> c2;
    public javax.swing.JComboBox<String> c3;
    public javax.swing.JComboBox<String> c4;
    public javax.swing.JComboBox<String> c5;
    public javax.swing.JComboBox<String> c6;
    public javax.swing.JComboBox<String> c7;
    public javax.swing.JComboBox<String> c8;
    public javax.swing.JComboBox<String> c9;
    public javax.swing.JButton gexit;
    public javax.swing.JButton gnext1;
    public javax.swing.JButton gpre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel net;
    public javax.swing.JComboBox<String> r1;
    public javax.swing.JComboBox<String> r10;
    public javax.swing.JComboBox<String> r2;
    public javax.swing.JComboBox<String> r3;
    public javax.swing.JComboBox<String> r4;
    public javax.swing.JComboBox<String> r5;
    public javax.swing.JComboBox<String> r6;
    public javax.swing.JComboBox<String> r7;
    public javax.swing.JComboBox<String> r8;
    public javax.swing.JComboBox<String> r9;
    public javax.swing.JTextField t1;
    public javax.swing.JTextField t10;
    public javax.swing.JTextField t2;
    public javax.swing.JTextField t3;
    public javax.swing.JTextField t4;
    public javax.swing.JTextField t5;
    public javax.swing.JTextField t6;
    public javax.swing.JTextField t7;
    public javax.swing.JTextField t8;
    public javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
