/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gpa;

import com.sun.corba.se.spi.orb.OperationFactory;
import java.awt.TextField;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Isuru Madhushan
 */
public class gpai extends javax.swing.JFrame {

public  int numsub;
public String name;
public String rnumber;
public String uniname;
public  String yearsem;


public int anumsub;
public String aname;
public String arnumber;
public  String auniname;
public String ayearsem;

    /**
     * Creates new form 
     */
    public gpai() {
        initComponents();
        setTitle("GPA Calculator");
        setIcon() ;
               
        
    }
    
   public gpai(int x,String a,String b,String c,String d){
       initComponents();
        setTitle("GPA Calculator");
        setIcon() ;
        
        anumsub=x;
        aname=a;
        arnumber=b;
        auniname=c;
        ayearsem=d;
        
        gname.setText(aname);
        gnumber.setText(arnumber);
        guni.setText(auniname);
        gyear1.setText(ayearsem);
        gsub.setText(Integer.toString(anumsub));
   }
 
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        guni = new javax.swing.JTextField();
        gname = new javax.swing.JTextField();
        gnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gyear1 = new javax.swing.JTextField();
        gexit = new javax.swing.JButton();
        gnext = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        gsub = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        net = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1362, 750));
        setPreferredSize(new java.awt.Dimension(1362, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 51));
        jLabel2.setText("GPA Calculator");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 570, 100));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Enter Your Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Enter Your Register number :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Enter Your University :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        guni.setBackground(new java.awt.Color(153, 255, 102));
        guni.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        guni.setForeground(new java.awt.Color(102, 51, 255));
        guni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guniActionPerformed(evt);
            }
        });
        guni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guniKeyPressed(evt);
            }
        });
        getContentPane().add(guni, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 920, -1));

        gname.setBackground(new java.awt.Color(153, 255, 102));
        gname.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        gname.setForeground(new java.awt.Color(102, 51, 255));
        gname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnameActionPerformed(evt);
            }
        });
        gname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gnameKeyPressed(evt);
            }
        });
        getContentPane().add(gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 920, -1));

        gnumber.setBackground(new java.awt.Color(153, 255, 102));
        gnumber.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        gnumber.setForeground(new java.awt.Color(102, 51, 255));
        gnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnumberActionPerformed(evt);
            }
        });
        gnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gnumberKeyPressed(evt);
            }
        });
        getContentPane().add(gnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 920, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("(Maximum number of subject is 10)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 530, -1));

        gyear1.setBackground(new java.awt.Color(153, 255, 102));
        gyear1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        gyear1.setForeground(new java.awt.Color(102, 51, 255));
        gyear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gyear1ActionPerformed(evt);
            }
        });
        gyear1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gyear1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gyear1KeyTyped(evt);
            }
        });
        getContentPane().add(gyear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 920, -1));

        gexit.setBackground(new java.awt.Color(0, 153, 204));
        gexit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        gexit.setForeground(new java.awt.Color(204, 204, 204));
        gexit.setText("Exit");
        gexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gexitActionPerformed(evt);
            }
        });
        gexit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gexitKeyPressed(evt);
            }
        });
        getContentPane().add(gexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 230, 60));

        gnext.setBackground(new java.awt.Color(0, 153, 204));
        gnext.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        gnext.setForeground(new java.awt.Color(204, 204, 204));
        gnext.setText("Next");
        gnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnextActionPerformed(evt);
            }
        });
        gnext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gnextKeyPressed(evt);
            }
        });
        getContentPane().add(gnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 230, 60));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Enter Examination Year and semester :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 340, 30));

        gsub.setBackground(new java.awt.Color(153, 255, 102));
        gsub.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        gsub.setForeground(new java.awt.Color(102, 51, 255));
        gsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsubActionPerformed(evt);
            }
        });
        gsub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gsubKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gsubKeyTyped(evt);
            }
        });
        getContentPane().add(gsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 920, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("Number Of Subject :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 220, -1));

        net.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gpa/dddddd.jpg"))); // NOI18N
        getContentPane().add(net, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void setIcon(){
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("download.png")));
    }
    private void guniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guniActionPerformed

    private void gnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnameActionPerformed

    private void gnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnumberActionPerformed

    private void gnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnameKeyPressed
    if(evt.getKeyCode()==10){
       gnumber.grabFocus();
    }  
    if(evt.getKeyCode()==40){
        gnumber.grabFocus();
    }
        
    
    }//GEN-LAST:event_gnameKeyPressed
 
   
    private void gyear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gyear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gyear1ActionPerformed

    private void gexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gexitActionPerformed
      this.dispose();
    }//GEN-LAST:event_gexitActionPerformed

    private void gnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnumberKeyPressed
        if(evt.getKeyCode()==10){
          guni.grabFocus();
        }
        if(evt.getKeyCode()==38){
           gname.grabFocus();
        }
        if(evt.getKeyCode()==40){
          guni.grabFocus();
        }
    }//GEN-LAST:event_gnumberKeyPressed

    private void guniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guniKeyPressed
         if(evt.getKeyCode()==10){
          gyear1.grabFocus();
        }
        if(evt.getKeyCode()==38){
           gnumber.grabFocus();
        }
        if(evt.getKeyCode()==40){
          gyear1.grabFocus();
        }
    }//GEN-LAST:event_guniKeyPressed

    private void gyear1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gyear1KeyPressed
        if(evt.getKeyCode()==10){
          gsub.grabFocus();
        }
        if(evt.getKeyCode()==38){
           guni.grabFocus();
        }
        if(evt.getKeyCode()==40){
          gsub.grabFocus();
        }
    }//GEN-LAST:event_gyear1KeyPressed

    private void gnextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnextKeyPressed
   if(evt.getKeyCode()==10){
          if(gname.getText().equals("") || gnumber.getText().equals("") || guni.getText().equals("") || gyear1.getText().equals("") || gsub.getText().equals("")) {
      JOptionPane.showMessageDialog(null," Please fill all fields ");
      }
      else{
         numsub=Integer.parseInt(gsub.getText());
           
      
       if(numsub<0 || numsub>10){
       JOptionPane.showMessageDialog(null, "Please Enter the number between 0 and 10");
       gsub.setText("");
       }
       else{
            name=gname.getText();
            rnumber=gnumber.getText();
            uniname=guni.getText();
            yearsem=gyear1.getText();
            
           
            
         gpa2 g21=new gpa2(numsub,name,rnumber,uniname,yearsem);
          this.dispose();
        g21.setVisible(true);
       }
      }
        }
        if(evt.getKeyCode()==38){
           gsub.grabFocus();
        }
        if(evt.getKeyCode()==39){
          gexit.grabFocus();
        }
        if(evt.getKeyCode()==40){
          gexit.grabFocus();
        }
        
        
    }//GEN-LAST:event_gnextKeyPressed

    private void gnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnextActionPerformed
      
        
      if(gname.getText().equals("") || gnumber.getText().equals("") || guni.getText().equals("") || gyear1.getText().equals("") || gsub.getText().equals("")) {
      JOptionPane.showMessageDialog(null," Please fill all fields ");
      }
      else{
         numsub=Integer.parseInt(gsub.getText());
          
       if(numsub<0 || numsub>10){
       JOptionPane.showMessageDialog(null, "Please Enter the number between 0 and 10");
       gsub.setText("");
       }
       else{
           
            name=gname.getText();
            rnumber=gnumber.getText();
            uniname=guni.getText();
            yearsem=gyear1.getText();
            
           
        
           gpa2 g22=new gpa2(numsub,name,rnumber,uniname,yearsem);
           
           g22.setVisible(true);
          this.dispose();
        
        
       }
     
      }
    }//GEN-LAST:event_gnextActionPerformed

    private void gsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsubActionPerformed

    private void gsubKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gsubKeyPressed
      if(evt.getKeyCode()==10){
        if(gname.getText().equals("") || gnumber.getText().equals("") || guni.getText().equals("") || gyear1.getText().equals("") || gsub.getText().equals("")) {
      JOptionPane.showMessageDialog(null," Please fill all fields ");
      }
      else{
         numsub=Integer.parseInt(gsub.getText());
       
        
       if(numsub<0 || numsub>10){
       JOptionPane.showMessageDialog(null, "Please Enter the number between 0 and 10");
       gsub.setText("");
       }
       else{
            name=gname.getText();
            rnumber=gnumber.getText();
            uniname=guni.getText();
            yearsem=gyear1.getText();
            
           
            
             gpa2 g23=new gpa2(numsub,name,rnumber,uniname,yearsem);
               
          this.dispose();
        g23.setVisible(true);
       }
      }
      }   
      if(evt.getKeyCode()==38){
      gyear1.grabFocus();
      }// TODO add your handling code here:
      if(evt.getKeyCode()==40){
      gnext.grabFocus();
      }
      
    }//GEN-LAST:event_gsubKeyPressed

    private void gexitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gexitKeyPressed
       if(evt.getKeyCode()==10){
       this.dispose();
      }   
      if(evt.getKeyCode()==38){
      gsub.grabFocus();
      }// TODO add your handling code here:
      if(evt.getKeyCode()==40){
      gname.grabFocus();
      }
      if(evt.getKeyCode()==37){
      gnext.grabFocus();
      }
      
    }//GEN-LAST:event_gexitKeyPressed

    private void gsubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gsubKeyTyped
       char enter=evt.getKeyChar();
       if(!(Character.isDigit(enter) )){
       evt.consume();
       }
       
       
       
       
    }//GEN-LAST:event_gsubKeyTyped

    private void gyear1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gyear1KeyTyped
       
    }//GEN-LAST:event_gyear1KeyTyped


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gpai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gpai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gpai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gpai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gpai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton gexit;
    public static javax.swing.JTextField gname;
    public javax.swing.JButton gnext;
    public static javax.swing.JTextField gnumber;
    public static javax.swing.JTextField gsub;
    public static javax.swing.JTextField guni;
    public static javax.swing.JTextField gyear1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel net;
    // End of variables declaration//GEN-END:variables
}
